[project]
name = "backend"
version = "0.1.0"
description = "FastAPI Chatbot Backend"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn>=0.23.2",
    "pydantic>=2.4.2"
]
