services:
#  caddy:
#    image: caddy:latest
#    restart: unless-stopped
#    ports:
#      - "80:80"
#      - "443:443"
#      - "443:443/udp"
#    volumes:
#      - ./docker/production/Caddyfile:/etc/caddy/Caddyfile
#      # - ./site:/srv  # Uncomment if you want to serve static files
#      - caddy_data:/data
#      - caddy_config:/config

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:8000"
    command: ["/app/.venv/bin/python3", "/app/src/chatbot_api/main.py", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers", "--forwarded-allow-ips=*"]
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      # Mount source code as volume for development
      # Comment out these lines in production
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      # Mount source code as volume for development
      # Comment out in production
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
